---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "web-application.fullname" . }}-vs
  namespace: {{ include "web-application.fullname" . }}
  labels:
    app: {{ include "web-application.fullname" . }}
    version: "{{ .Values.image.tag | default .Chart.AppVersion }}"
    backstage.io/kubernetes-id: {{ include "web-application.fullname" . }}
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - {{ include "web-application.fullname" . }}.diegoluisi.eti.br
  http:
  - name: primary
    route:
    - destination:
        host: {{ include "web-application.fullname" . }}-svc
        subset: stable
      weight: 100
    - destination:
        host: {{ include "web-application.fullname" . }}-svc
        subset: canary  # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
      weight: 0